---
title: "PS270 Final Project"
author: "Wade Lindmark"
description: "A Study On the Modern American Political Partisanship"
output:
  distill::distill_article:
    self_contained: false
---

##Thoughts on my Research

I am interested in exploring data related to political partisanship. We are presently living in an America where people have vastly different perceptions of the other party, demonizing one side or the other. If I can find some studies on it, I think I can do some solid research and come to good conclusions about the state of American polarization today.

##Progress #2

My research question is this:

How has the usage of media over time contributed to political partisanship in the United States?

My hypothesis is that as media has developed over time, from print media to radio to television to our phones, it has paradoxically driven us further apart from one another because it has become so easy to take what is seen on social media or the mainstream media as true. In essence, my hypothesis is that, as media has developed, political partisanship has increased, and will continue to. 

In order to measure this, my explanatory value will be a time-series data set that will observe individuals' use of media sources/outlets over time, and how those sources/outlets themselves' leanings have changed over time.

For my variable of interest, I want to look at polarization indicators observing how a given individual affiliated with a certain party changes their degree of distrust towards the opposition party, or by tracking respondents' beliefs of what the other side thinks of themselves through cognitive dissonance. I would measure it by asking respondents to answer where they believe the other party falls on a certain issue, with 1 being least extreme and 100 being most extreme.

If the observed pattern demonstrates that individuals who are largely gathering information from very partisan outlets are progressively growing in their distrust of the opposition party or of their key positions. For the sources themselves, it would show their readers/viewers having more distrust for the opposition the farther away from center the source shifts.

If a pattern were to show that media sources shifting their ideology is not correlated with increased rates of distrust of the opposition among their readers/viewers, or if individuals' usage of more partisan news sources over time does not indicate increased distrust towards the opposition, those indicators would disprove my hypothesis.